import whatsappWeb from 'whatsapp-web.js';
const { Client, LocalAuth } = whatsappWeb;
import QRCode from 'qrcode';
import fs from 'fs';
import path from 'path';
import { logger } from './utils/logger.js';
import { db } from './firebase.js';
import { normalizePhoneNumber, phoneToJid } from './utils/phone.js';

export type WhatsAppState =
  | 'INITIALIZING'
  | 'QR_REQUIRED'
  | 'AUTHENTICATING'
  | 'READY'
  | 'DISCONNECTED'
  | 'AUTH_FAILURE'
  | 'ERROR';

export interface WhatsAppClientStatus {
  status: WhatsAppState;
  qrDataUrl: string | null;
  phoneNumber: string | null;
  user: { name?: string; id?: string } | null;
  lastConnectedAt: string | null;
  error: string | null;
}

let clientInstance: whatsappWeb.Client | null = null;
let currentStatus: WhatsAppState = 'INITIALIZING';
let currentRawQr: string | null = null;
let currentQrDataUrl: string | null = null;
let connectedNumber: string | null = null;
let connectedUser: { name?: string; id?: string } | null = null;
let lastConnectedAt: string | null = null;
let lastError: string | null = null;

const AUTH_DIR = path.join(process.cwd(), '.wwebjs_auth');

export function getWhatsAppStatus(): WhatsAppClientStatus {
  return {
    status: currentStatus,
    qrDataUrl: currentQrDataUrl,
    phoneNumber: connectedNumber,
    user: connectedUser,
    lastConnectedAt,
    error: lastError,
  };
}

export function getWhatsAppQr() {
  if (currentStatus === 'QR_REQUIRED' && (currentRawQr || currentQrDataUrl)) {
    return {
      available: true,
      status: 'qr_required',
      qr: currentRawQr || currentQrDataUrl,
      qrDataUrl: currentQrDataUrl,
    };
  }
  return {
    available: false,
    status: currentStatus.toLowerCase(),
    qr: null,
    qrDataUrl: null,
  };
}

async function syncStatusToFirestore(clinicId = 'clinic-flagship') {
  try {
    if (!db) return;
    const docRef = db.collection('whatsappConnections').doc(clinicId);
    await docRef.set(
      {
        status: currentStatus,
        qrDataUrl: currentQrDataUrl,
        phoneNumber: connectedNumber,
        user: connectedUser,
        lastConnectedAt: lastConnectedAt ? new Date(lastConnectedAt) : null,
        updatedAt: new Date(),
        error: lastError,
      },
      { merge: true }
    );
  } catch (err) {
    logger.error({ err }, 'Failed to sync WhatsApp status to Firestore');
  }
}

export async function initializeWhatsAppClient(clinicId = 'clinic-flagship'): Promise<WhatsAppClientStatus> {
  if (clientInstance && currentStatus === 'READY') {
    return getWhatsAppStatus();
  }

  currentStatus = 'QR_REQUIRED';
  currentQrDataUrl = null;
  lastError = null;

  await syncStatusToFirestore(clinicId);

  try {
    if (!fs.existsSync(AUTH_DIR)) {
      fs.mkdirSync(AUTH_DIR, { recursive: true });
    }

    if (clientInstance) {
      try {
        await clientInstance.destroy();
      } catch (e) {
        logger.warn({ err: e }, 'Error destroying previous WhatsApp client instance');
      }
      clientInstance = null;
    }

    const execPath =
      process.env.PUPPETEER_EXECUTABLE_PATH && fs.existsSync(process.env.PUPPETEER_EXECUTABLE_PATH)
        ? process.env.PUPPETEER_EXECUTABLE_PATH
        : undefined;

    clientInstance = new Client({
      authStrategy: new LocalAuth({
        clientId: clinicId,
        dataPath: AUTH_DIR,
      }),
      puppeteer: {
        headless: true,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-accelerated-2d-canvas',
          '--no-first-run',
          '--no-zygote',
          '--disable-gpu',
        ],
        executablePath: execPath,
      },
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    });

    clientInstance.on('qr', async (qr) => {
      logger.info('WhatsApp QR Code generated by whatsapp-web.js.');
      currentStatus = 'QR_REQUIRED';
      currentRawQr = qr;
      try {
        currentQrDataUrl = await QRCode.toDataURL(qr, {
          margin: 2,
          width: 280,
          color: { dark: '#0b2e78', light: '#ffffff' },
        });
      } catch (e: any) {
        logger.error({ err: e }, 'Failed to convert QR string to data URL');
      }
      await syncStatusToFirestore(clinicId);
    });

    clientInstance.on('authenticated', () => {
      logger.info('WhatsApp client authenticated.');
      currentStatus = 'AUTHENTICATING';
      currentRawQr = null;
      currentQrDataUrl = null;
      syncStatusToFirestore(clinicId);
    });

    clientInstance.on('auth_failure', (msg) => {
      logger.error(`WhatsApp authentication failure: ${msg}`);
      currentStatus = 'AUTH_FAILURE';
      currentRawQr = null;
      lastError = msg || 'Authentication failed';
      syncStatusToFirestore(clinicId);
    });

    clientInstance.on('ready', () => {
      logger.info('WhatsApp Client is READY!');
      currentStatus = 'READY';
      currentRawQr = null;
      currentQrDataUrl = null;
      lastConnectedAt = new Date().toISOString();

      if (clientInstance?.info) {
        connectedNumber = clientInstance.info.wid.user;
        connectedUser = {
          name: clientInstance.info.pushname || `Teethly Clinic (+${connectedNumber})`,
          id: clientInstance.info.wid._serialized,
        };
      }
      syncStatusToFirestore(clinicId);
    });

    clientInstance.on('disconnected', (reason) => {
      logger.warn({ reason }, 'WhatsApp Client disconnected');
      currentStatus = 'DISCONNECTED';
      currentQrDataUrl = null;
      connectedNumber = null;
      connectedUser = null;
      syncStatusToFirestore(clinicId);
    });

    // Start client in background (do not block)
    clientInstance.initialize().catch((err) => {
      logger.error({ err }, 'Failed to initialize WhatsApp client instance');
      currentStatus = 'ERROR';
      lastError = err.message || 'Failed to start Chromium browser';
      syncStatusToFirestore(clinicId);
    });
  } catch (err: any) {
    logger.error({ err }, 'Error setting up WhatsApp client');
    currentStatus = 'ERROR';
    lastError = err.message || 'Failed to initialize WhatsApp Web Client';
    await syncStatusToFirestore(clinicId);
  }

  return getWhatsAppStatus();
}

export function simulatePairWhatsAppClient(clinicId = 'clinic-flagship'): WhatsAppClientStatus {
  currentStatus = 'READY';
  currentQrDataUrl = null;
  connectedNumber = '15553368672';
  connectedUser = {
    name: 'Teethly Main Clinic (+1 555-Teethly)',
    id: '15553368672@s.whatsapp.net',
  };
  lastConnectedAt = new Date().toISOString();
  lastError = null;
  syncStatusToFirestore(clinicId);
  return getWhatsAppStatus();
}

export async function sendWhatsAppMessage(rawPhone: string, text: string): Promise<string> {
  if (currentStatus !== 'READY' || !clientInstance) {
    throw new Error(`WhatsApp Client is not READY (Current state: ${currentStatus}). Please scan the QR code first.`);
  }

  const normalized = normalizePhoneNumber(rawPhone);
  if (!normalized) {
    throw new Error('Invalid phone number provided for WhatsApp dispatch.');
  }

  const jid = phoneToJid(normalized);

  try {
    const response = await clientInstance.sendMessage(jid, text);
    logger.info({ jid, msgId: response.id.id }, 'WhatsApp message dispatched successfully');
    return response.id.id;
  } catch (err: any) {
    logger.error({ err, jid }, 'Failed to send WhatsApp message via whatsapp-web.js');
    throw new Error(err.message || 'WhatsApp Web JS send failure');
  }
}

export async function disconnectWhatsAppClient(clinicId = 'clinic-flagship'): Promise<boolean> {
  try {
    if (clientInstance) {
      await clientInstance.destroy();
      clientInstance = null;
    }
    currentStatus = 'DISCONNECTED';
    currentQrDataUrl = null;
    connectedNumber = null;
    connectedUser = null;
    await syncStatusToFirestore(clinicId);
    return true;
  } catch (err: any) {
    logger.error({ err }, 'Error disconnecting WhatsApp client');
    return false;
  }
}
